spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    hikari:
      maximum-pool-size: ${db.maximum-pool-size}
      connection-timeout: ${db.connection-timeout}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: companies-crud
  profiles:
    active: default
  config:
    import: "optional:configserver:http://localhost:7777"
server:
  servlet:
    context-path: /companies-crud
  port: 0
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service:
      defaultZones: http://localhost:8761/eureka/
